# Generated by Django 5.0.4 on 2024-09-27 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleBrand",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("status", models.BooleanField(default=False)),
                ("logo", models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.vehiclebrand"
            ),
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("status", models.BooleanField(default=False)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.vehiclebrand",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.vehiclemodel"
            ),
        ),
    ]
