# Generated by Django 5.0.4 on 2024-09-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_vehiclebrand_alter_vehicle_brand_vehiclemodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
