# Generated by Django 5.0.4 on 2024-09-27 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.service",
            ),
            preserve_default=False,
        ),
    ]
