# Generated by Django 5.0.4 on 2024-09-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_appointment_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
