# Generated by Django 5.0.4 on 2024-09-28 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_vehicle_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="fuel_entry",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DamagePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_x", models.FloatField()),
                ("position_y", models.FloatField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damage_positions",
                        to="base.appointment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehiclePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="vehicle_photos/")),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="base.appointment",
                    ),
                ),
            ],
        ),
    ]
