# Generated by Django 5.0.4 on 2024-09-30 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_alter_appointment_branch_alter_appointment_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="vehicle",
            name="color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.vehiclecolor",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="year",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.vehicleyear",
            ),
        ),
    ]
