# Generated by Django 5.0.4 on 2024-10-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_vehiclecolor_vehicleyear_vehicle_color_vehicle_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="mileage",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
