# Generated by Django 5.0.4 on 2024-10-10 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_appointment_mileage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checklist",
            old_name="extinguisher",
            new_name="botiquin",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="first_aid_kit",
            new_name="documentos",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="front_collision",
            new_name="extintor",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="jack",
            new_name="gata",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="left_side_collision",
            new_name="herramientas",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="rear_collision",
            new_name="llave_rueda",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="right_side_collision",
            new_name="neumatico_repuesto",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="spare_tire",
            new_name="triangulos",
        ),
        migrations.RemoveField(
            model_name="checklist",
            name="triangles",
        ),
    ]
