# Generated by Django 5.0.4 on 2024-10-10 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_rename_extinguisher_checklist_botiquin_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checklist",
            old_name="botiquin",
            new_name="documents",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="documentos",
            new_name="extinguisher",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="extintor",
            new_name="first_aid_kit",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="gata",
            new_name="jack",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="herramientas",
            new_name="spare_tire",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="llave_rueda",
            new_name="tools",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="neumatico_repuesto",
            new_name="triangles",
        ),
        migrations.RenameField(
            model_name="checklist",
            old_name="triangulos",
            new_name="wheel_key",
        ),
    ]
