# Generated by Django 5.0.4 on 2024-10-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_rename_botiquin_checklist_documents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="status",
            field=models.CharField(
                choices=[
                    ("In progress", "En progreso"),
                    ("Waiting for parts", "Esperando piezas"),
                    ("Completed", "Completado"),
                ],
                default="In progress",
                max_length=50,
            ),
        ),
    ]
