# Generated by Django 5.0.4 on 2024-10-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0013_alter_work_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="status",
            field=models.CharField(
                choices=[
                    ("En progreso", "In progress"),
                    ("Esperando piezas", "Waiting for parts"),
                    ("Completado", "Completed"),
                ],
                default="In progress",
                max_length=50,
            ),
        ),
    ]
