# Generated by Django 5.0.4 on 2024-10-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0016_alter_work_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="points",
            name="redemption_code",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
