# Generated by Django 5.0.4 on 2024-10-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0017_points_redemption_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mechanic",
            options={
                "ordering": ["name"],
                "verbose_name": "Mechanic",
                "verbose_name_plural": "Mechanics",
            },
        ),
        migrations.AddField(
            model_name="mechanic",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="mechanic",
            name="experience_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mechanic",
            name="hire_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="mechanic",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="mechanic",
            name="specialty",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Received", "Received"),
                    ("In progress", "In progress"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
