# Generated by Django 5.0.4 on 2024-10-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0018_alter_mechanic_options_mechanic_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mechanic",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="mechanic",
            name="hire_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="mechanic",
            name="specialty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Electricista", "Electricista"),
                    ("Mecánico", "Mecánico"),
                    ("Mecatrónico", "Mecatrónico"),
                    ("Lubricador", "Lubricador"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
