# Generated by Django 5.0.4 on 2024-10-15 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0019_alter_mechanic_email_alter_mechanic_hire_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanic",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mechanics",
                to="base.branch",
            ),
        ),
    ]
