# Generated by Django 5.0.4 on 2024-10-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0020_mechanic_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name="News",
        ),
    ]
