# Generated by Django 5.0.4 on 2024-10-17 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0022_work_end_date_work_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="start_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
