# Generated by Django 5.0.4 on 2024-10-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0023_alter_work_end_date_alter_work_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="priority",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default="Medium",
                max_length=10,
            ),
        ),
    ]
